### ISSUE TITLE
Multiple images on a listing not obvious

### ISSUE THREAD

**Issue by JohnVeness** [Freegle/iznik-client#13]
Currently, if there are multiple images attached to a listing, on the web site the thumbnail will automatically cycle through them, with a period of approximately 10 seconds. If you click on an image thumbnail, you see a larger version of that image (which doesn't automatically cycle). On an email, you will see just the first thumbnail.

This means that, at the moment, it is quite easy to not notice that there are multiple images, if you don't sit and look at the website version of the listing for more than 10 seconds. This can be a problem if you're not sure whether an item is what you want, or not.

I suggest, on the email version, maybe adding some text like "+2 other images" when appropriate under the thumbnail. On the website, again maybe some similar text under the thumbnail. And when clicking on any of the thumbnails to show a larger version, have left and right arrows, or Prev and Next buttons, which will show the other images when clicked. Maybe even have a "filmstrip" showing multiple thumbnails under a larger image like ebay does.

**Comment by edwh** [comment]
Thanks for this suggestion. I entirely agree, and have a private todo item covering similar ground. So I hope to be able to do something in this area fairly soon.

**Comment by edwh** [comment]
This is in place now.  Thanks for the suggestion.
