### ISSUE TITLE
Volunteering prompt doubles-up

### ISSUE THREAD

**Issue by codepotato** [Freegle/iznik-client#15]
Just navigated through the site and noticed that either you're really keen to get people to donate their time, or there's a bug in the rendering of this element! 

<img width="942" alt="screen shot 2018-11-08 at 10 38 59" src="https://user-images.githubusercontent.com/417524/48193566-aa576100-e342-11e8-8790-476f85ab4d8d.png">

**Comment by edwh** [comment]
I don't see that - can you get a repro series of steps starting from a 
page refresh?

------ Original Message ------

**Comment by edwh** [comment]
That should be fixed now; will go live shortly.
