### ISSUE TITLE
Missing documentation for running iznik-client locally

### ISSUE THREAD

**Issue by bernhard-hofmann** [Freegle/iznik-client#4]
I thought I saw this documentation somewhere but cannot find it now. The documentation should explain how a contributor would run the client locally to test changes before they submit a pull request (or, currently, commit and push)?

**Comment by edwh** [comment]
Are you thinking of the info that on the home page of the repository, at https://github.com/Freegle/iznik-client ?

**Comment by edwh** [comment]
In terms of whether it's a pull request or a commit/push, then for the people we already "know", they have access and can do a push; for people who we don't, they can do a pull request.  Perhaps we could say that, though isn't that standard?
