### ISSUE TITLE
Explore page group list not updating

### ISSUE THREAD

**Issue by edwh** [Freegle/iznik-client#6]
If you go to the Explore page, you see the map of all groups, and a list of all of them lower down.  

If you use the search box, then the map adjusts and shows the groups near there, but sometimes the list still shows all of them.  

This will be a timing window where the fetch for the groups for the lower list is in progress, which stops us fetching again, or something.

**Comment by bernhard-hofmann** [comment]
Which is the `Explore` page, or how do I reach it?
Found it! https://www.ilovefreegle.org/explore

**Comment by edwh** [comment]
Go to www.ilovefreegle.org, click Explore, takes you to www.ilovefreegle.org/explore

**Comment by edwh** [comment]
Fixed this.
